/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/no-explicit-any */
import { IJoin } from "./component.default.interface";
import { IMenuConfiguracoes } from "./menu-configuracoes.interface";

export class FormField<T> {
  value: any;
  key: any;
  label: string;
  required: boolean;
  validator: string;
  order: number;
  controlType: string;
  type: string;
  options: { key: number; value: string; class?: string }[];
  rota_options: string;
  key_options: string;
  value_options: string;
  size: string;
  placeholder: string;
  isDateType: boolean;
  default_options_type: string;
  add_new: boolean;
  component: IMenuConfiguracoes;
  isTimeDate: boolean;
  isHourType: boolean;
  isCurrency: boolean;
  multSelect: boolean;
  optionLabel: string;
  optionValue: string;
  exibeFiltro: boolean;
  exibeForm: boolean;
  joins: IJoin;
  dc_legenda: any;
  set_data_atual: boolean;
  disabled: boolean;
  withInput: string;
  isDateRangeType: boolean;
  dateRangeInit: string;
  dateRangeEnd: string;
  isNotUpdated: boolean;
  isCPF: boolean;
  isTelefone: boolean;
  isCelular: boolean;
  isCEP: boolean;
  isSearchable: boolean;
  searchKey: string;
  searchID: string;
  searchLabel: string;
  exibeSearch: boolean;
  isDateTimeTZ: boolean;
  isSetValue: boolean;
  set_value: any;
  operador: string;
  whereRes: IJoin;
  setValueInField: boolean;
  setValueInFieldKey: string;
  setValueInFieldValue: any;
  habilitaInput: boolean;
  habilitaInputKey: string;
  habilitaInputValue: any;
  isFutureDate: boolean;
  isWereRes: boolean;
  searchElemento: any;
  desabilitaInput: boolean;
  desabilitaInputKey: string;
  isAtivos: boolean;
  searchValue: string;

  constructor(
    options: {
      value?: any;
      key?: any;
      label?: string;
      required?: boolean;
      validator?: string;
      order?: number;
      controlType?: string;
      type?: string;
      options?: { key: any; value: string; class?: string }[];
      rota_options?: string;
      key_options?: string;
      value_options?: string;
      size?: string;
      placeholder?: string;
      isDateType?: boolean;
      default_options_type?: string;
      add_new?: boolean;
      component?: IMenuConfiguracoes;
      isTimeDate?: boolean;
      isHourType?: boolean;
      isCurrency?: boolean;
      multSelect?: boolean;
      optionLabel?: string;
      optionValue?: string;
      exibeFiltro?: boolean;
      exibeForm?: boolean;
      joins?: IJoin;
      dc_legenda?: any;
      set_data_atual?: boolean;
      disabled?: boolean;
      withInput?: string;
      isDateRangeType?: boolean;
      dateRangeInit?: string;
      dateRangeEnd?: string;
      isNotUpdated?: boolean;
      isCPF?: boolean;
      isTelefone?: boolean;
      isCelular?: boolean;
      isCEP?: boolean;
      isSearchable?: boolean;
      searchKey?: string;
      searchID?: string;
      searchLabel?: string;
      exibeSearch?: boolean;
      isDateTimeTZ?: boolean;
      isSetValue?: boolean;
      set_value?: any;
      operador?: string;
      whereRes?: IJoin;
      setValueInField?: boolean;
      setValueInFieldKey?: string;
      setValueInFieldValue?: any;
      habilitaInput?: boolean;
      habilitaInputKey?: string;
      habilitaInputValue?: any;
      isFutureDate?: boolean;
      isWereRes?: boolean;
      searchElemento?: any;
      desabilitaInput?: boolean;
      desabilitaInputKey?: string;
      isAtivos?: boolean;
      searchValue?: string;
    } = {}
  ) {
    this.value = options.value;
    this.key = options.key || null;
    this.label = options.label || "";
    this.required = !!options.required;
    this.validator = options.validator || "";
    this.order = options.order === undefined ? 1 : options.order;
    this.controlType = options.controlType || "";
    this.type = options.type || "";
    this.options = options.options || [];
    this.rota_options = options.rota_options || "";
    this.key_options = options.key_options || "";
    this.value_options = options.value_options || "";
    this.size = options.size || "";
    this.placeholder = options.placeholder || "";
    this.isDateType = options.isDateType || false;
    this.isHourType = options.isHourType || false;
    this.default_options_type = options.default_options_type || "";
    this.add_new = options.add_new || false;
    this.component = options.component || {};
    this.isTimeDate = options.isTimeDate || false;
    this.isCurrency = options.isCurrency || false;
    this.multSelect = options.multSelect || false;
    this.optionLabel = options.optionLabel || "";
    this.optionValue = options.optionValue || "";
    this.exibeFiltro = options.exibeFiltro || false;
    this.exibeForm = options.exibeForm || false;
    this.joins = options.joins || {};
    this.dc_legenda = options.dc_legenda || "";
    this.set_data_atual = options.set_data_atual || false;
    this.disabled = options.disabled || false;
    this.withInput = options.withInput || "";
    this.isDateRangeType = options.isDateRangeType || false;
    this.dateRangeInit = options.dateRangeInit || "";
    this.dateRangeEnd = options.dateRangeEnd || "";
    this.isNotUpdated = options.isNotUpdated || false;
    this.isCPF = options.isCPF || false;
    this.isTelefone = options.isTelefone || false;
    this.isCelular = options.isCelular || false;
    this.isCEP = options.isCEP || false;
    this.isSearchable = options.isSearchable || false;
    this.searchKey = options.searchKey || "";
    this.searchID = options.searchID || "";
    this.searchLabel = options.searchLabel || "";
    this.exibeSearch = options.exibeSearch || false;
    this.isDateTimeTZ = options.isDateTimeTZ || false;
    this.isSetValue = options.isSetValue || false;
    this.set_value = options.set_value || null;
    this.operador = options.operador || "";
    this.whereRes = options.whereRes || {};
    this.setValueInField = options.setValueInField || false;
    this.setValueInFieldKey = options.setValueInFieldKey || "";
    this.setValueInFieldValue = options.setValueInFieldValue || null;
    this.habilitaInput = options.habilitaInput || false;
    this.habilitaInputKey = options.habilitaInputKey || "";
    this.habilitaInputValue = options.habilitaInputValue || null;
    this.isFutureDate = options.isFutureDate || false;
    this.isWereRes = options.isWereRes || false;
    this.searchElemento = options.searchElemento || null;
    this.desabilitaInput = options.desabilitaInput || false;
    this.desabilitaInputKey = options.desabilitaInputKey || "";
    this.isAtivos = options.isAtivos || false;
    this.searchValue = options.searchValue || "";
  }
}
